### ISSUE TITLE
crt0stack

### ISSUE THREAD

**Issue by haraldh** [phip1611/linux-libc-auxv#2]
Interesting crate :) Have you seen this? https://github.com/enarx/crt0stack/

**Comment by phip1611** [comment]
hi @haraldh ,
thanks! I'm talking about `crt0stack` in the README of this crate. From what I see, `crt0stack` does not allow creating the stack layout for another address space unfortunately which makes it unsuitable to create a stack layout for another process (when creating a Linux OS personality for example).

**Comment by haraldh** [comment]
oops.. didn't read it all 👍

**Comment by phip1611** [comment]
No problem :) @haraldh
